networks:
  app-tier:
    driver: bridge

services:
  fastapi:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    networks:
      - app-tier

  celery:
    build: .
    command: celery -A app.core.celery_con worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    networks:
      - app-tier

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-tier

  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-tier

  tests:
    build: .
    volumes:
      - .:/app
    command: pytest -v
    depends_on:
      - redis
      - celery
      - db
    networks:
      - app-tier


volumes:
  postgres_data:
