"""rocket3

Revision ID: 0698ea4e2bc5
Revises: 1054d511854c
Create Date: 2025-03-10 10:58:18.781700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0698ea4e2bc5"
down_revision: Union[str, None] = "1054d511854c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Rocket", sa.Column("time_start", sa.DateTime(), nullable=True))
    op.add_column("Rocket", sa.Column("time_uspel", sa.DateTime(), nullable=True))
    op.drop_column("Rocket", "time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Rocket",
        sa.Column("time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.drop_column("Rocket", "time_uspel")
    op.drop_column("Rocket", "time_start")
    # ### end Alembic commands ###
