"""v5

Revision ID: 081d78abfeee
Revises: f3a86d38b7c1
Create Date: 2025-01-31 22:57:08.494502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081d78abfeee'
down_revision: Union[str, None] = 'f3a86d38b7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('last_enter', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Account_data_balance'), 'Account_data', ['balance'], unique=False)
    op.create_index(op.f('ix_Account_data_email'), 'Account_data', ['email'], unique=True)
    op.create_index(op.f('ix_Account_data_id'), 'Account_data', ['id'], unique=False)
    op.create_index(op.f('ix_Account_data_status'), 'Account_data', ['status'], unique=False)
    op.add_column('User_data', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User_data', 'Account_data', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User_data', type_='foreignkey')
    op.drop_column('User_data', 'account_id')
    op.drop_index(op.f('ix_Account_data_status'), table_name='Account_data')
    op.drop_index(op.f('ix_Account_data_id'), table_name='Account_data')
    op.drop_index(op.f('ix_Account_data_email'), table_name='Account_data')
    op.drop_index(op.f('ix_Account_data_balance'), table_name='Account_data')
    op.drop_table('Account_data')
    # ### end Alembic commands ###
