"""rocket2

Revision ID: 1054d511854c
Revises: feaab5a092cd
Create Date: 2025-03-08 13:43:33.319928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1054d511854c'
down_revision: Union[str, None] = 'feaab5a092cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Rocket_rocketX', table_name='Rocket')
    op.drop_column('Rocket', 'rocketX')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Rocket', sa.Column('rocketX', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_Rocket_rocketX', 'Rocket', ['rocketX'], unique=False)
    # ### end Alembic commands ###
