"""1

Revision ID: 3efb23e43971
Revises: 
Create Date: 2025-01-28 22:58:49.871683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efb23e43971'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trade_Result', sa.Column('trade_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Trade_Result_trade_id'), 'Trade_Result', ['trade_id'], unique=True)
    op.drop_constraint('Trade_data_result_fkey', 'Trade_data', type_='foreignkey')
    op.create_foreign_key(None, 'Trade_data', 'Trade_Result', ['result'], ['trade_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Trade_data', type_='foreignkey')
    op.create_foreign_key('Trade_data_result_fkey', 'Trade_data', 'Trade_Result', ['result'], ['id'])
    op.drop_index(op.f('ix_Trade_Result_trade_id'), table_name='Trade_Result')
    op.drop_column('Trade_Result', 'trade_id')
    # ### end Alembic commands ###
