"""add Rocket

Revision ID: 54971b2592c2
Revises: 89d687c6f2ee
Create Date: 2025-03-03 05:33:05.570873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54971b2592c2'
down_revision: Union[str, None] = '89d687c6f2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rocket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_price', sa.Float(), nullable=True),
    sa.Column('end_price', sa.Float(), nullable=True),
    sa.Column('uspel', sa.Boolean(), nullable=True),
    sa.Column('rocketX', sa.Float(), nullable=True),
    sa.Column('endX', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Rocket_id'), 'Rocket', ['id'], unique=False)
    op.create_index(op.f('ix_Rocket_start_price'), 'Rocket', ['start_price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Rocket_start_price'), table_name='Rocket')
    op.drop_index(op.f('ix_Rocket_id'), table_name='Rocket')
    op.drop_table('Rocket')
    # ### end Alembic commands ###
