"""1

Revision ID: 6f21d1bd6d39
Revises: 
Create Date: 2025-01-29 12:40:30.172735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f21d1bd6d39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trade_Result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('trade_result', sa.String(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Trade_Result_id'), 'Trade_Result', ['id'], unique=False)
    op.create_index(op.f('ix_Trade_Result_money'), 'Trade_Result', ['money'], unique=False)
    op.create_index(op.f('ix_Trade_Result_trade_id'), 'Trade_Result', ['trade_id'], unique=True)
    op.create_index(op.f('ix_Trade_Result_trade_result'), 'Trade_Result', ['trade_result'], unique=False)
    op.create_table('User_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_data_id'), 'User_data', ['id'], unique=False)
    op.create_index(op.f('ix_User_data_username'), 'User_data', ['username'], unique=False)
    op.create_table('Trade_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('bet_amount', sa.Float(), nullable=True),
    sa.Column('leverageX', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('start_price', sa.Float(), nullable=True),
    sa.Column('end_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result'], ['Trade_Result.trade_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Trade_data_bet_amount'), 'Trade_data', ['bet_amount'], unique=False)
    op.create_index(op.f('ix_Trade_data_exchange'), 'Trade_data', ['exchange'], unique=False)
    op.create_index(op.f('ix_Trade_data_id'), 'Trade_data', ['id'], unique=False)
    op.create_index(op.f('ix_Trade_data_status'), 'Trade_data', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Trade_data_status'), table_name='Trade_data')
    op.drop_index(op.f('ix_Trade_data_id'), table_name='Trade_data')
    op.drop_index(op.f('ix_Trade_data_exchange'), table_name='Trade_data')
    op.drop_index(op.f('ix_Trade_data_bet_amount'), table_name='Trade_data')
    op.drop_table('Trade_data')
    op.drop_index(op.f('ix_User_data_username'), table_name='User_data')
    op.drop_index(op.f('ix_User_data_id'), table_name='User_data')
    op.drop_table('User_data')
    op.drop_index(op.f('ix_Trade_Result_trade_result'), table_name='Trade_Result')
    op.drop_index(op.f('ix_Trade_Result_trade_id'), table_name='Trade_Result')
    op.drop_index(op.f('ix_Trade_Result_money'), table_name='Trade_Result')
    op.drop_index(op.f('ix_Trade_Result_id'), table_name='Trade_Result')
    op.drop_table('Trade_Result')
    # ### end Alembic commands ###
