"""v7

Revision ID: 76c4a6174582
Revises: 9bcf9f26ecac
Create Date: 2025-02-01 13:36:21.737552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c4a6174582'
down_revision: Union[str, None] = '9bcf9f26ecac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Account_data', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Account_data_account_id'), 'Account_data', ['account_id'], unique=True)
    op.drop_index('ix_User_data_username', table_name='User_data')
    op.create_index(op.f('ix_User_data_username'), 'User_data', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_data_username'), table_name='User_data')
    op.create_index('ix_User_data_username', 'User_data', ['username'], unique=False)
    op.drop_index(op.f('ix_Account_data_account_id'), table_name='Account_data')
    op.drop_column('Account_data', 'account_id')
    # ### end Alembic commands ###
