"""rocket4

Revision ID: b87c975d5f60
Revises: 0698ea4e2bc5
Create Date: 2025-03-11 07:09:16.975638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87c975d5f60'
down_revision: Union[str, None] = '0698ea4e2bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Rocket', sa.Column('time_start_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Rocket', 'time_start_start')
    # ### end Alembic commands ###
