"""21

Revision ID: f3a86d38b7c1
Revises: 9972d81def9b
Create Date: 2025-01-29 23:15:55.210293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a86d38b7c1'
down_revision: Union[str, None] = '9972d81def9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trade_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('end_price', sa.Float(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Trade_result_id'), 'Trade_result', ['id'], unique=False)
    op.create_index(op.f('ix_Trade_result_money'), 'Trade_result', ['money'], unique=False)
    op.create_index(op.f('ix_Trade_result_trade_id'), 'Trade_result', ['trade_id'], unique=True)
    op.create_table('Trade_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('bet_amount', sa.Float(), nullable=True),
    sa.Column('leverageX', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('start_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trade_result', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result'], ['Trade_result.trade_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Trade_data_bet_amount'), 'Trade_data', ['bet_amount'], unique=False)
    op.create_index(op.f('ix_Trade_data_exchange'), 'Trade_data', ['exchange'], unique=False)
    op.create_index(op.f('ix_Trade_data_id'), 'Trade_data', ['id'], unique=False)
    op.create_index(op.f('ix_Trade_data_status'), 'Trade_data', ['status'], unique=False)
    op.create_index(op.f('ix_Trade_data_trade_result'), 'Trade_data', ['trade_result'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Trade_data_trade_result'), table_name='Trade_data')
    op.drop_index(op.f('ix_Trade_data_status'), table_name='Trade_data')
    op.drop_index(op.f('ix_Trade_data_id'), table_name='Trade_data')
    op.drop_index(op.f('ix_Trade_data_exchange'), table_name='Trade_data')
    op.drop_index(op.f('ix_Trade_data_bet_amount'), table_name='Trade_data')
    op.drop_table('Trade_data')
    op.drop_index(op.f('ix_Trade_result_trade_id'), table_name='Trade_result')
    op.drop_index(op.f('ix_Trade_result_money'), table_name='Trade_result')
    op.drop_index(op.f('ix_Trade_result_id'), table_name='Trade_result')
    op.drop_table('Trade_result')
    # ### end Alembic commands ###
