"""v8

Revision ID: fb23809593f7
Revises: 76c4a6174582
Create Date: 2025-02-01 13:40:18.578728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb23809593f7'
down_revision: Union[str, None] = '76c4a6174582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_data_account_id_fkey', 'User_data', type_='foreignkey')
    op.create_foreign_key(None, 'User_data', 'Account_data', ['account_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User_data', type_='foreignkey')
    op.create_foreign_key('User_data_account_id_fkey', 'User_data', 'Account_data', ['account_id'], ['id'])
    # ### end Alembic commands ###
