"""rocket1

Revision ID: feaab5a092cd
Revises: 54971b2592c2
Create Date: 2025-03-06 11:19:07.879758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "feaab5a092cd"
down_revision: Union[str, None] = "54971b2592c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Rocket", sa.Column("start_bet", sa.Float(), nullable=True))
    op.add_column("Rocket", sa.Column("end_bet", sa.Float(), nullable=True))
    op.add_column("Rocket", sa.Column("zabrannyyX", sa.Float(), nullable=True))
    op.drop_index("ix_Rocket_start_price", table_name="Rocket")
    op.create_index(op.f("ix_Rocket_end_bet"), "Rocket", ["end_bet"], unique=False)
    op.create_index(op.f("ix_Rocket_rocketX"), "Rocket", ["rocketX"], unique=False)
    op.create_index(op.f("ix_Rocket_start_bet"), "Rocket", ["start_bet"], unique=False)
    op.create_index(op.f("ix_Rocket_uspel"), "Rocket", ["uspel"], unique=False)
    op.create_index(
        op.f("ix_Rocket_zabrannyyX"), "Rocket", ["zabrannyyX"], unique=False
    )
    op.drop_column("Rocket", "start_price")
    op.drop_column("Rocket", "end_price")
    op.drop_column("Rocket", "endX")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Rocket",
        sa.Column(
            "endX",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "Rocket",
        sa.Column(
            "end_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "Rocket",
        sa.Column(
            "start_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_Rocket_zabrannyyX"), table_name="Rocket")
    op.drop_index(op.f("ix_Rocket_uspel"), table_name="Rocket")
    op.drop_index(op.f("ix_Rocket_start_bet"), table_name="Rocket")
    op.drop_index(op.f("ix_Rocket_rocketX"), table_name="Rocket")
    op.drop_index(op.f("ix_Rocket_end_bet"), table_name="Rocket")
    op.create_index("ix_Rocket_start_price", "Rocket", ["start_price"], unique=False)
    op.drop_column("Rocket", "zabrannyyX")
    op.drop_column("Rocket", "end_bet")
    op.drop_column("Rocket", "start_bet")
    # ### end Alembic commands ###
